# Continut
## 0. Importul bibliotecilor
## 1. Tipuri de date si atribute
## 2. Crearea unui array NumPy
## 3. Vizualizarea in array si matrici
## 4. Manipularea si compararea array
## 5. Utilizarea NumPy: Vanzare Fructe
## 6. Sortarea in array
## 7. Conversia imaginii in array

# 0. Importul bibliotecilor

In [274]:
# importul bibliotecilor utilizate
import numpy as np
import pandas as pd
from matplotlib.image import imread

# 1. Tipuri de date si atribute

### 1.1. Tipuri de date NumPy
#### Principalul tip de date in NumPy este tipul ndarray

In [2]:
# crearea unui array unidimensional
a1 = np.array([1, 2, 3])

In [3]:
# vizualizarea lui a1
a1

array([1, 2, 3])

In [4]:
# crearea unui array bidimensional
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [5]:
# crearea unui array tridimensional
a3 = np.array([[[1, 2, 3],
                [4, 5, 6]],
               [[7, 8, 9],
                [10, 11, 12]],
               [[13, 14, 15],
                [16, 17, 18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

### 1.2. Atributele elementelor de tip ndarray
#### 1.2.1. Forma ndarray - `.shape`

In [6]:
# vizualizarea formei lui a1
a1.shape

(3,)

In [7]:
# vizualizarea formei lui a2
a2.shape

(2, 3)

In [8]:
# vizualizarea formei lui a3
a3.shape

(3, 2, 3)

#### 1.2.2. Numarul dimensiunii - `.ndim`

In [9]:
# vizualizarea numarului de dimensiuni pentru a1
a1.ndim

1

In [10]:
# vizualizarea numarului de dimensiuni pentru a2
a2.ndim

2

In [11]:
# vizualizarea numarului de dimensiuni pentru a3
a3.ndim

3

#### 1.2.3. Tipul elementelor componente - `.dtype`

In [12]:
# determinarea tipului elementelor lui a1
a1.dtype

dtype('int32')

In [13]:
# determinarea tipului elementelor lui a2
a2.dtype

dtype('float64')

In [14]:
# determinarea tipului elementelor lui a3
a3.dtype

dtype('int32')

#### 1.2.4. Numarul elementelor componente - `.size`

In [15]:
# determinarea numarului de elemente in a1
a1.size

3

In [16]:
# determinarea numarului de elemente in a2
a2.size

6

In [17]:
# determinarea numarului de elemente in a3
a3.size

18

#### 1.2.5. Tipul array - `type()`

In [18]:
# determinarea tipului lui a1
type(a1)

numpy.ndarray

In [19]:
# determinarea tipului lui a2
type(a2)

numpy.ndarray

In [20]:
# determinarea tipului lui a3
type(a3)

numpy.ndarray

### 1.3. Transformarea unui array in dataframe

In [22]:
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

# 2. Crearea unui array NumPy

### 2.1. Crearea unui array cu ajutorul listelor

In [26]:
# se creaza 2 liste Python
lt1 = [6, 2, 8, 4]
lt2 = [7, 9, 3, 5]
lt1, lt2

([6, 2, 8, 4], [7, 9, 3, 5])

In [27]:
# se creaza un array unidimensional din lt1
ar1=np.array(lt1)
ar1

array([6, 2, 8, 4])

In [29]:
# se creaza un array bidimensional din lt1 si lt2
ar2=np.array([lt1,lt2])
ar2

array([[6, 2, 8, 4],
       [7, 9, 3, 5]])

### 2.2. Crearea unui array din elemente 1 sau 0

In [101]:
# se creaza o variabila ce specifica forma array
sp = (3,5)
sp

(3, 5)

In [102]:
# se creaza un array doar din elemente 1
ar3 = np.ones(sp)
ar3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [103]:
# se creaza un array doar din elemente 0
ar4 = np.zeros(sp)
ar4

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### 2.3. Crearea unui array cu elemente dintr-un interval

In [35]:
# se creaza un array unidimensional cu elementele intregi de la 0 la 9
ar5 =  np.arange(10)
ar5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
# se creaza un array unidimensional cu elementele intregi de la 5 la 9
ar6 =  np.arange(5, 10)
ar6

array([5, 6, 7, 8, 9])

In [37]:
# se creaza un array unidimensional cu elementele intregi de la 4 la 9 luate cu pasul 2
ar7 =  np.arange(4, 10, 2)
ar7

array([4, 6, 8])

In [245]:
# se creaza un array format din 20 de elemente situate uniform in intervalul 0 - 10
arr12 = np.linspace(0, 10, 20)
arr12

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

### 2.4. Crearea unui array cu elemente random

In [104]:
# se creaza un array bidimensional cu elementele random intregi de la 2 la 9
ar8 =  np.random.randint(2, 10, size=sp)
ar8

array([[5, 5, 7, 5, 8],
       [9, 3, 2, 2, 3],
       [9, 2, 7, 5, 4]])

In [105]:
# se creaza un array bidimensional cu elementele random float de la 0 la 0,999...
ar9 =  np.random.random(sp)
ar9

array([[0.079316  , 0.06766956, 0.49097967, 0.20946683, 0.92522345],
       [0.98061055, 0.66963061, 0.58175139, 0.79431745, 0.04670004],
       [0.58026021, 0.07451129, 0.16007004, 0.43488873, 0.59376418]])

In [43]:
# se creaza un array n-dimensional cu elementele random float de la 0 la 0,999...
ar10 =  np.random.rand(2, 4, 5)
ar10

array([[[0.69615431, 0.6308812 , 0.30878104, 0.07752817, 0.59377636],
        [0.62473911, 0.9669843 , 0.35940954, 0.09028768, 0.29817828],
        [0.96203645, 0.52321626, 0.72639501, 0.50117861, 0.19708768],
        [0.81551691, 0.87542428, 0.64359532, 0.88718885, 0.61950226]],

       [[0.92555634, 0.6499454 , 0.9608929 , 0.36543233, 0.21517459],
        [0.76141817, 0.66780822, 0.63661828, 0.25300245, 0.81364713],
        [0.41096415, 0.98691844, 0.18878282, 0.20240595, 0.73303543],
        [0.17480585, 0.14338244, 0.79320081, 0.23380053, 0.17598422]]])

### 2.5. Setarea elementelor pseudo-random

In [96]:
# se creaza un array cu elementele random
ar11=np.random.random((4,5))
ar11

array([[0.67781654, 0.27000797, 0.73519402, 0.96218855, 0.24875314],
       [0.57615733, 0.59204193, 0.57225191, 0.22308163, 0.95274901],
       [0.44712538, 0.84640867, 0.69947928, 0.29743695, 0.81379782],
       [0.39650574, 0.8811032 , 0.58127287, 0.88173536, 0.69253159]])

In [97]:
# se repeta procedura de creare a aceluiasi array
ar11=np.random.random((4,5))
ar11

array([[0.72525428, 0.50132438, 0.95608363, 0.6439902 , 0.42385505],
       [0.60639321, 0.0191932 , 0.30157482, 0.66017354, 0.29007761],
       [0.61801543, 0.4287687 , 0.13547406, 0.29828233, 0.56996491],
       [0.59087276, 0.57432525, 0.65320082, 0.65210327, 0.43141844]])

In [98]:
# seteaza numerele random sa fie pseudo-random si se repeta procedura
np.random.seed(9)
ar11=np.random.random((4,5))
ar11

array([[0.01037415, 0.50187459, 0.49577329, 0.13382953, 0.14211109],
       [0.21855868, 0.41850818, 0.24810117, 0.08405965, 0.34549864],
       [0.16677635, 0.87855909, 0.95096403, 0.03874838, 0.69910739],
       [0.57275982, 0.89800712, 0.66689897, 0.54783778, 0.70242742]])

In [100]:
# se repeta procedura de creare a aceluiasi array cu pseudo-random
np.random.seed(9)
ar11=np.random.random((4,5))
ar11

array([[0.01037415, 0.50187459, 0.49577329, 0.13382953, 0.14211109],
       [0.21855868, 0.41850818, 0.24810117, 0.08405965, 0.34549864],
       [0.16677635, 0.87855909, 0.95096403, 0.03874838, 0.69910739],
       [0.57275982, 0.89800712, 0.66689897, 0.54783778, 0.70242742]])

# 3. Vizualizarea in array si matrici

### 3.1. Vizualizarea elementelor unice in array

In [199]:
# se vizualizeaza ar8
ar8

array([[5, 5, 7, 5, 8],
       [9, 3, 2, 2, 3],
       [9, 2, 7, 5, 4]])

In [109]:
# determinarea elementelor unice in ar8
np.unique(ar8)

array([2, 3, 4, 5, 7, 8, 9])

### 3.2. Selectarea elementelor unui array conform indicelui

In [111]:
# vizualizarea lui a1
a1

array([1, 2, 3])

In [112]:
# selectarea elementului de pe pozitia a 2
a1[1]

2

In [113]:
# vizualizarea lui a2
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [114]:
# selectarea elementelor liniei a 2
a2[1]

array([4. , 5. , 6.5])

In [115]:
# selectarea elementului de pe linia a 2 poztia 1
a2[1,0]

4.0

In [116]:
# vizualizarea lui a3
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [118]:
# selectarea elementului din tabelul 3 linia a 1 pozitia 2
a3[2,0,1]

14

### 3.3. Selectarea elementelor unui array folosind slicing

In [121]:
# selectarea primelor 2 elemente ale lui a1
a1[:2]

array([1, 2])

In [122]:
# selectarea primelor elemente din priele 2 linie al lui a2
a2[:2,:1]

array([[1.],
       [4.]])

In [123]:
# selectarea primelor 2 elemente din primele linii al primelor 2 tabele
a3[:2,:1,:2]

array([[[1, 2]],

       [[7, 8]]])

# 4. Manipularea si compararea array

### 4.1. Operatii aritmetice "element cu element"

In [124]:
# Vizualizarea a1
a1

array([1, 2, 3])

In [125]:
# creara unui array unidimensional
a4 = np.array([7, 9, 3])
a4

array([7, 9, 3])

In [126]:
# Sumarea a1 ai a4 si formarea a5
a5 = a1 + a4
a5

array([ 8, 11,  6])

In [141]:
# Sumarea a1 ai a4 si folosind functia np.add()
a5 = np.add(a1, a4)
a5

array([ 8, 11,  6])

In [128]:
# Scaderea lui a1 din a4 si formarea a6
a6 = a4 - a1
a6

array([6, 7, 0])

In [131]:
# Imultirea a1 cu a6 si formarea a7
a7 = a1 * a6
a7

array([ 6, 14,  0])

In [133]:
# Vizualizarea a2
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [134]:
# Imultirea a2 cu a6 si formarea a8
a8 = a2 * a6
a8

array([[ 6., 14.,  0.],
       [24., 35.,  0.]])

In [137]:
# Impartirea a5 la a1 si formarea a9
a9 = a5 / a1
a9

array([8. , 5.5, 2. ])

In [138]:
# Impartirea cu rotungire a5 la a1 si formarea a10
a10 = a5 // a1
a10

array([8, 5, 2], dtype=int32)

In [139]:
# Ridicarea lui a2 la patrat
a11 = a2 **2
a11

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [140]:
# Ridicarea lui a2 la patrat utilizand functia np.square()
a12=np.square(a2)
a12

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [142]:
# Determinarea restului divizarii lui a2 la 2
a13 = a2 % 2
a13

array([[1. , 0. , 1.3],
       [0. , 1. , 0.5]])

In [143]:
# Determinarea exponentei lui a1
a14 = np.exp(a1)
a14

array([ 2.71828183,  7.3890561 , 20.08553692])

In [146]:
# Determinarea logaritmului natural al lui a1
a15 = np.log(a1)
a15

array([0.        , 0.69314718, 1.09861229])

### 4.2. Operatii de agregare

In [149]:
# vizualizare lui a10
a10

array([8, 5, 2], dtype=int32)

In [150]:
# Determinarea sumei tuturor elemtelor cu functia sum() din python
sum(a10)

15

In [151]:
# Determinarea sumei tuturor elemtelor cu functia sum() din numpy
np.sum(a10)

15

In [152]:
# crearea unui array imens
arr_imens = np.random.random(100000)

In [153]:
# vizualizarea numarului de elemnte in arr_imens
arr_imens.size

100000

In [154]:
# vizualizarea primelor 10 elemente
arr_imens[:10]

array([0.14015816, 0.89892299, 0.97871952, 0.92973789, 0.39278113,
       0.28933945, 0.31675249, 0.98689438, 0.04285168, 0.17011414])

In [155]:
# determinarea timpului de executie a operatiei sum() din python cu functia magica %timeit
%timeit sum(arr_imens)

5.37 ms ± 57.8 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [156]:
# determinarea timpului de executie a operatiei np.sum() din numpy cu functia magica %timeit
%timeit np.sum(arr_imens)

32 µs ± 331 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [157]:
# determinarea raportului dintre timpul de executie a opertiilor python si numpy
5370/32

167.8125

In [159]:
# vizualizare lui a2
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [160]:
# Determinarea valorii medii a elementelor din a2
np.mean(a2)

3.6333333333333333

In [161]:
# Determinarea valorii maxime a elementelor din a2
np.max(a2)

6.5

In [162]:
# Determinarea valorii minime a elementelor din a2
np.min(a2)

1.0

In [163]:
# Determinarea valorii abaterii medii standart a tuturor elementelor din a2
np.std(a2)

1.8226964152656422

In [164]:
# Determinarea valorii abaterii medii standart a elementelor pe coloane in a2
np.std(a2, axis=0)

array([1.5, 1.5, 1.6])

In [165]:
# Determinarea valorii abaterii medii standart a elementelor pe linie in a2
np.std(a2, axis=1)

array([0.94162979, 1.02740233])

In [166]:
# Determinarea valorii abaterii medii patratice a tuturor elementelor din a2
np.var(a2)

3.3222222222222224

In [167]:
# Determinarea valorii abaterii medii patratice a elementelor pe linie in a2
np.var(a2, axis=1)

array([0.88666667, 1.05555556])

In [171]:
np.sqrt(1.05555556)

1.027402335991115

### 4.3. Modificare formei unui array

Cand se realizaza operatii cu doua variabile de tip array, NumPy compara formele acestora, iar pentru aceasta trebuie sa se respecte una din cele 2 reguli
* formele trebuie sa fie identice
* o dimensiune trebuie sa fie 1

In [172]:
# vizualizarea lui a2
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [173]:
# vizualizarea formei lui a2
a2.shape

(2, 3)

In [174]:
# vizualizarea numarului dimensiunii lui a2
a2.ndim

2

In [180]:
# vizualizarea lui a3
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [181]:
# vizualizarea formei lui a3
a3.shape

(3, 2, 3)

In [182]:
# vizualizarea numarului dimensiunii lui a3
a3.ndim

3

Daca se incerca imultirea a2*a3 se obtine o eroare deoarece formele nu respecta nici una din cele 2 reguli 

In [183]:
# modificarea formei lui a2
a6 = a2.reshape(1,2,3)
a6

array([[[1. , 2. , 3.3],
        [4. , 5. , 6.5]]])

In [184]:
# vizualizarea formei lui a6
a6.shape

(1, 2, 3)

In [185]:
# vizualizarea numarului dimensiunii lui a6
a6.ndim

3

In [186]:
# se realizeaza operatia de imultirea a2*a3
a2*a3

array([[[  1. ,   4. ,   9.9],
        [ 16. ,  25. ,  39. ]],

       [[  7. ,  16. ,  29.7],
        [ 40. ,  55. ,  78. ]],

       [[ 13. ,  28. ,  49.5],
        [ 64. ,  85. , 117. ]]])

### 4.4. Transpusa  unui array

In [187]:
# vizualizarea lui a2
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [188]:
# vizualizarea formei lui a2
a2.shape

(2, 3)

In [189]:
# vizualizarea numarului dimensiunii lui a2
a2.ndim

2

In [190]:
# obtinerea transpusei lui a2
a7 = a2.T
a7

array([[1. , 4. ],
       [2. , 5. ],
       [3.3, 6.5]])

In [191]:
# vizualizarea formei lui a7
a7.shape

(3, 2)

In [192]:
# vizualizarea numarului dimensiunii lui a7
a7.ndim

2

### 4.5. Operatorul DOT product

In [194]:
# se creaza 2 matrice de aceleasi dimensiuni
np.random.seed(9)

mat1=np.random.randint(10, size=(3,4))
mat2=np.random.randint(10, size=(3,4))

In [195]:
# vizualizarea lui mat1
mat1

array([[5, 6, 8, 6],
       [1, 6, 4, 8],
       [1, 8, 5, 1]])

In [196]:
# vizualizarea lui mat2
mat2

array([[0, 8, 8, 8],
       [2, 6, 8, 1],
       [8, 3, 5, 3]])

In [198]:
# vizualizarea formelor lui mat1 si mat2
mat1.shape, mat2.shape

((3, 4), (3, 4))

In [197]:
# imultirea "element cu element" a mat1 si mat2 (Hadamard product)
mat1 * mat2

array([[ 0, 48, 64, 48],
       [ 2, 36, 32,  8],
       [ 8, 24, 25,  3]])

Pentru realizarea operatiei `DOT product` dintre 2 matrici de formele (m,n) si (x,y) este necesar ca n=x iar matricea rezultanta va avea forma (m,y).
Mai multe se pot gasi pe adresele:
https://www.mathsisfun.com/algebra/matrix-multiplying.html

http://matrixmultiplication.xyz/

In [202]:
# determinarea transpusei lui m2
mat2_T = mat2.T
mat2_T

array([[0, 2, 8],
       [8, 6, 3],
       [8, 8, 5],
       [8, 1, 3]])

In [203]:
# vizualizarea formei lui mat2_T
mat2_T.shape

(4, 3)

In [204]:
# realizarea operatiei dot product dintre mat1 si mat2_T
mat3 = np.dot(mat1, mat2_T)
mat3

array([[160, 116, 116],
       [144,  78,  70],
       [112,  91,  60]])

In [205]:
# vizualizarea formei lui mat3
mat3.shape

(3, 3)

In [206]:
# realizarea operatiei dot product dintre mat2_T si mat1
mat4 = np.dot(mat2_T, mat1)
mat4

array([[ 10,  76,  48,  24],
       [ 49, 108, 103,  99],
       [ 53, 136, 121, 117],
       [ 44,  78,  83,  59]])

In [207]:
# vizualizarea formei lui mat4
mat4.shape

(4, 4)

### 4.6. Comparison Operators 

In [235]:
# vizualizarea lui a1
a1

array([1, 2, 3])

In [236]:
# vizualizarea lui a2
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [237]:
# compararea a1 cu a2
a1 > a2

array([[False, False, False],
       [False, False, False]])

In [238]:
# compararea a1 cu a2 si formarea lui a11
a11 = a1 >= a2
a11

array([[ True,  True, False],
       [False, False, False]])

In [239]:
# vizualizarea tipului lui a11
type(a11)

numpy.ndarray

In [240]:
# vizualizarea tipului elementelor lui a11
a11.dtype

dtype('bool')

In [242]:
# compararea a2 cu un numar scalar
a2 >= 5

array([[False, False, False],
       [False,  True,  True]])

In [243]:
# compararea a2 cu a2
a2 == a2

array([[ True,  True,  True],
       [ True,  True,  True]])

# 5. Utilizarea NumPy: Vanzare Fructe

In exemplu se determina cati lei s-au obtinut zilnic din vanzarea a trei tipuri de fructe: cirese, capsune si zmeura. Cantitatea vanzarilor si pretul per kg sunt specificate in fisierul Vanzari_fructe.xlsx

In [209]:
# se creaza o matrice NumPy cu vanzarile zilnice:
vanzari_cantitate= np.array([[20, 14, 23], 
                             [31, 41, 14],
                             [15, 21, 34],
                             [19, 21, 26],
                             [13, 17, 11],
                             [23, 14, 6],
                             [27, 18, 9]])
vanzari_cantitate

array([[20, 14, 23],
       [31, 41, 14],
       [15, 21, 34],
       [19, 21, 26],
       [13, 17, 11],
       [23, 14,  6],
       [27, 18,  9]])

In [217]:
# se vizualizeaza forma si numarul de dimensiuni a lui vanzari_cantitate
vanzari_cantitate.shape, vanzari_cantitate.ndim

((7, 3), 2)

In [211]:
# pentru o vizualizare mai adecvata se va forma un dataframe pentru vanzari_cantitate
vc_df= pd.DataFrame(vanzari_cantitate,
                    index=['Luni', 'Marti', 'Miercuri', 'Joi', 'Vineri', 'Sambata', 'Duminica'],
                    columns = ['Cirese (kg)', 'Capsune (kg)', 'Zmeura (kg)'])
vc_df

Cirese (kg)  Capsune (kg)  Zmeura (kg)
Luni               20            14           23
Marti              31            41           14
Miercuri           15            21           34
Joi                19            21           26
Vineri             13            17           11
Sambata            23            14            6
Duminica           27            18            9

In [210]:
# se creaza un array cu preturile per kg a fructelor:
pret_kg = np.array([20, 25, 32])

In [216]:
# se vizualizeaza forma si numarul de dimensiuni a lui pret_kg
pret_kg.shape, pret_kg.ndim

((3,), 1)

In [218]:
# se modifica forma lui pret_kg
pret_kg_m = pret_kg.reshape(1,3)
pret_kg_m

array([[20, 25, 32]])

In [219]:
# pentru o vizualizare mai adecvata se va forma un dataframe si pentru pret_kg 
pret_df= pd.DataFrame(pret_kg_m ,
                    index=['Pret (lei/kg)'],
                    columns = ['Cirese', 'Capsune', 'Zmeura'])
pret_df

Cirese  Capsune  Zmeura
Pret (lei/kg)      20       25      32

In [233]:
# se vizualizeaza forma lui pret_kg
pret_kg.shape

(3,)

In [226]:
# se vizualizeaza forma lui vanzari_cantitate
vanzari_cantitate.shape

(7, 3)

In [227]:
# se determina transpusa lui vanzari_cantitate
vanzari_cantitate_T = vanzari_cantitate.T
vanzari_cantitate_T

array([[20, 31, 15, 19, 13, 23, 27],
       [14, 41, 21, 21, 17, 14, 18],
       [23, 14, 34, 26, 11,  6,  9]])

In [228]:
# se vizualizeaza forma lui vanzari_cantitate_T
vanzari_cantitate_T.shape

(3, 7)

In [231]:
# se determina suma zinica obtinuta utilizand operantul dot product
suma_zilnica = pret_kg.dot (vanzari_cantitate_T)
suma_zilnica

array([1486, 2093, 1913, 1737, 1037, 1002, 1278])

In [234]:
# Adaugarea unei noi coloane cu suma zilnica in vc_df
vc_df['Total (lei)'] = suma_zilnica
vc_df

Cirese (kg)  Capsune (kg)  Zmeura (kg)  Total (lei)
Luni               20            14           23         1486
Marti              31            41           14         2093
Miercuri           15            21           34         1913
Joi                19            21           26         1737
Vineri             13            17           11         1037
Sambata            23            14            6         1002
Duminica           27            18            9         1278

# 6. Sortarea in array

In [246]:
# vizualizarea lui ar8
ar8

array([[5, 5, 7, 5, 8],
       [9, 3, 2, 2, 3],
       [9, 2, 7, 5, 4]])

In [247]:
# sortarea elementelor lui ar8 pe linii
np.sort(ar8, axis=1)

array([[5, 5, 5, 7, 8],
       [2, 2, 3, 3, 9],
       [2, 4, 5, 7, 9]])

In [248]:
# sortarea elementelor lui ar8 pe coloane
np.sort(ar8, axis=0)

array([[5, 2, 2, 2, 3],
       [9, 3, 7, 5, 4],
       [9, 5, 7, 5, 8]])

In [252]:
# obtinerea unui array cu indicii elementelor daca s-ar realiza sortarea pe linie
np.argsort(ar8, axis=1)

array([[0, 1, 3, 2, 4],
       [2, 3, 1, 4, 0],
       [1, 4, 3, 2, 0]], dtype=int64)

In [253]:
# obtinerea unui array cu indicii elementelor daca s-ar realiza sortarea pe linie
np.argsort(ar8, axis=0)

array([[0, 2, 1, 1, 1],
       [1, 1, 0, 0, 2],
       [2, 0, 2, 2, 0]], dtype=int64)

In [256]:
# determinarea indexului celui mai mic element pe linii
np.argmin(ar8, axis=1)

array([0, 2, 1], dtype=int64)

In [257]:
# determinarea indexului celui mai mic element pe coloane
np.argmin(ar8, axis=0)

array([0, 2, 1, 1, 1], dtype=int64)

In [258]:
# determinarea indexului celui mai mic element in array
np.argmin(ar8)

7

In [259]:
# determinarea indexului celui mai mare element pe linii
np.argmax(ar8, axis=1)

array([4, 0, 0], dtype=int64)

In [260]:
# determinarea indexului celui mai mare element pe coloane
np.argmax(ar8, axis=0)

array([1, 0, 0, 0, 0], dtype=int64)

In [261]:
# determinarea indexului celui mai mare element in array
np.argmax(ar8)

5

# 7. Conversia imaginii in array

In exemplu de mai jos se va realiza conversia imaginii rosa_image.jpg in array adica conversia imaginii in valori numerice


<img src="trandafir_image.jpg"/>

In [263]:
# importul bibliotecii corespunzatoare
from matplotlib.image import imread

In [271]:
# conversia imaginii in array specificat calea catre imagine
trandafir = imread("trandafir_image.jpg")
trandafir

array([[[176,  78,  91],
        [176,  80,  92],
        [176,  83,  94],
        ...,
        [165, 171, 161],
        [164, 170, 160],
        [163, 169, 159]],

       [[175,  77,  90],
        [175,  79,  91],
        [175,  82,  93],
        ...,
        [164, 170, 160],
        [163, 169, 159],
        [162, 168, 158]],

       [[172,  74,  87],
        [174,  76,  89],
        [174,  78,  90],
        ...,
        [161, 167, 157],
        [160, 166, 156],
        [159, 165, 155]],

       ...,

       [[ 57,  81,  31],
        [ 58,  82,  32],
        [ 60,  84,  34],
        ...,
        [ 58,  82,  60],
        [ 58,  82,  60],
        [ 58,  82,  60]],

       [[ 57,  84,  33],
        [ 58,  85,  34],
        [ 59,  86,  35],
        ...,
        [ 62,  87,  65],
        [ 62,  87,  65],
        [ 62,  87,  65]],

       [[ 58,  85,  34],
        [ 59,  86,  35],
        [ 60,  87,  36],
        ...,
        [ 65,  90,  68],
        [ 65,  90,  68],
        [ 65,  90,  68]]

In [265]:
# vizualizarea tipului lui trandafir
type(trandafir)

numpy.ndarray

In [266]:
# vizualizarea formei lui trandafir
trandafir.shape

(447, 600, 3)

In [267]:
# vizualizarea numarului dimensiunii lui trandafir
trandafir.ndim

3

In [268]:
# vizualizarea numarului de elemente in trandafir
trandafir.size

804600

In [270]:
# vizualizarea tipului elementelor in trandafir
trandafir.dtype

dtype('uint8')